import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from '../../styles/testimonials.module.scss'



function testimonials(params) {

    const fields = [
        {
          name: 'name*',
          type: 'text',
          placeholder: 'Enter your name'
        },
        {
          name: 'email',
          type: 'email',
          placeholder: 'Enter your email'
        },
        {
          name: 'subject',
          type: 'text',
          placeholder: 'Type the subject'
        },
        {
          name: 'message',
          type: 'textarea',
          placeholder: 'Type your message here...'
        }
      ]


      const images = [
        {
            url: '/images/testimonials1_before.png'
        },
        {
            url: '/images/testimonials1_after.png'
        },
        {
            url: '/images/testimonials2_before.png'
        },
        {
            url: '/images/testimonials2_after.png'
        },
        {
            url: '/images/testimonials3_before.png'
        },
        {
            url: '/images/testimonials3_after.png'
        },
        {
            url: '/images/testimonials4_before.png'
        },
        {
            url: '/images/testimonials4_after.png'
        },
        {
            url: '/images/testimonials5_before.png'
        },
        {
            url: '/images/testimonials5_after.png'
        },
      ]


return(
<>
    <Head>
        <title>Alex D's Cleaning Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconAlex.ico" />
    </Head>
    <div>
        <Navbar/>
    </div>

    <div className={styles.indicator_container}>
        <div>
        <h1>Testimonials</h1>
        <p>Examples of High Quality Services We Provide</p>
        </div>
    </div>


    <div className={styles.gallery_container}>
        <div>
            {
                images.map((image) => (
                    <Image src={image.url} width='300' height={'300'} ></Image>
                ))
            }
        </div>
    </div>

    <div className={styles.form_container}>
        <div>

          <div>
            <h2>
            Get a Free Quote Now!
            </h2>
            <p>Questions, comments or requests? Feel free to reach out, we’d love to hear from you.</p>
            <div>
            <p>Humble, texas</p>
            <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
            <a href="tel:+12392343355">(239)-234-3355</a>
            </div>

          </div>
            
            <form action="">
                {
                  fields.map((field) => (
                    <div>
                        <label htmlFor="">{field.name}</label>
                      {
                      field.type == 'text' || field.type == 'email' ?
                      <input type={field.type} placeholder={field.placeholder} />: 
                      <textarea placeholder={field.placeholder} ></textarea>
                      }
                    </div>
                  ))
                }

                <button>submit</button>
            </form>





        </div>

    </div>


    <div className={styles.nav_container}>
    <Link href='/about'>about us</Link>
    <Link href='/services'>services</Link>
    <Link href='/testimonials'>testimonials</Link>
    <Link href='/contact'>contact us</Link>
    </div>

    <footer className={styles.footer}>
    <div>
        <h1><Link href={'/'}>Alex D's Cleaning Service LLC</Link></h1>

        <div>
        <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
        <a href="tel:+12392343355">(239)-234-3355</a>
        </div>

        <p>©2023 by Alex D's Cleaning Service LLC.</p>
    </div>
    </footer>
</>
)
    
}


export default testimonials;