import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from '../../styles/services.module.scss'




function Services(params) {

    const fields = [
        {
          name: 'name*',
          type: 'text',
          placeholder: 'Enter your name'
        },
        {
          name: 'address',
          type: 'text',
          placeholder: 'Enter your address'
        },
        {
          name: 'email',
          type: 'email',
          placeholder: 'Enter your email',
        //   class: 'half_width'
        },
        {
          name: 'phone*',
          type: 'text',
          placeholder: 'Enter your phone number',
        //   class: 'half_width'
        },
        {
          name: 'subject',
          type: 'text',
          placeholder: 'Type the subject'
        },
        {
          name: 'message',
          type: 'textarea',
          placeholder: 'Type your message here...'
        }
      ]


      
      const cards = [
        {
            title: 'Home cleanings',
            paragraph: 'If you are moving into or out of your apartment or house, we can easily lessen the stress of your move by making sure your home is ready for the next family.',
            image: '/../public/images/home_cleaning2.jpg'
        },
        {
            title: 'Vacation rentals and Air bnb\'s cleanings',
            paragraph: '',
            image: '/../public/images/rentals_cleaning.jpg'
        },
        {
            title: 'Recurring cleanings',
            paragraph: 'Depending on your preference, we offer weekly, bi-weekly, and monthly cleanings. These routine cleanings allow us to efficiently and effectively tackle dirt and dust build up.',
            image: '/../public/images/recurring_cleaning.jpg'
        },
        {
            title: 'Window, Carpet and pressure cleanings',
            paragraph: '',
            image: '/../public/images/pressure_cleaning3.jpg'
        },
        {
            title: 'Deep Cleaning',
            paragraph: 'We highly recommend our deep cleaning services as a stand alone service or before a recurring cleaning. This service includes deep cleaning baseboards, deep cleaning bathrooms, and wiping down window blinds just to name a few',
            image: '/../public/images/deep_cleaning.jpg'
        },
        {
            title: 'Additional services',
            paragraph: 'We also offer additional services such as interior and exterior window cleaning, interior fridge cleaning, oven cleaning, etc that are not normally included in our other services.',
            image: '/../public/images/additional_services.jpg'
        },
    ]
    
    return(
        <>
            <Head>
                <title>Alex D's Cleaning Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/faviconAlex.ico" />
            </Head>
            <div >
                <Navbar/>
            </div>

            <div className={styles.indicator_container}>
                <h1>Our Cleaning Services</h1>
                <p>Bluebonnet Cleaning is dedicated to providing 
                    high quality services to the Greater Houston area through 
                    residential and commercial cleaning. Take a look below to find 
                    out what we specialize in and get in touch if you have any additional 
                    questions or to learn more information.
                </p>
            </div>

            <div className={styles.cards_container}>
                {
                    cards.map((card) => (
                        <div>
                            <Image src={card.image} width='300' height={'300'} ></Image>
                            <h2>{card.title}</h2>
                            <p>{card.paragraph}</p>
                        </div>
                    ))
                }
            </div>

            <div className={styles.form_container}>
                <div className={styles.bg_container}></div>
                <div className={styles.form_container}>
                    <div>

                        <div>
                            <h2>
                            Get a Quote!
                            </h2>
                            <div>
                            <p>Let us know what type of service you are looking for. We are more than happy to help!</p>
                            </div>
                        </div>
                    
                        <form action="">
                            {
                            fields.map((field) => (
                                <div className={styles[field.class]}>
                                    <label htmlFor="">{field.name}</label>
                                {
                                field.type == 'text' || field.type == 'email' ?
                                <input type={field.type} placeholder={field.placeholder} />: 
                                <textarea placeholder={field.placeholder} ></textarea>
                                }
                                </div>
                            ))
                            }

                            <button>submit</button>
                        </form>

                    </div>
                </div>
            </div>

            
            <div className={styles.nav_container}>
            <Link href='/about'>about us</Link>
            <Link href='/services'>services</Link>
            <Link href='/testimonials'>testimonials</Link>
            <Link href='/contact'>contact us</Link>
            </div>

            <footer className={styles.footer}>
            <div>
            <h1><Link href={'/'}>Alex D's Cleaning Service LLC</Link></h1>

            <div>
            <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
            <a href="tel:+12392343355">(239)-234-3355</a>
            </div>

            <p>©2023 by Alex D's Cleaning Service LLC.</p>
            </div>
            </footer>
        </>
    )
}


export default Services;