import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Navbar from "../components/Navbar";
import Carousel from "../components/carousel";
import Link from 'next/link';
import vector1 from '../public/vectors/world.png'
import vector2 from '../public/vectors/mop.png'
import vector3 from '../public/vectors/spray.png'
import vector4 from '../public/vectors/hand.png'


export default function Home() {

  const fields = [
    {
      name: 'name*',
      type: 'text',
      placeholder: 'Enter your name'
    },
    {
      name: 'address',
      type: 'text',
      placeholder: 'Enter your address'
    },
    {
      name: 'email',
      type: 'email',
      placeholder: 'Enter your email'
    },
    {
      name: 'phone*',
      type: 'text',
      placeholder: 'Enter your phone number'
    },
    {
      name: 'subject',
      type: 'text',
      placeholder: 'Type the subject'
    },
    {
      name: 'message',
      type: 'textarea',
      placeholder: 'Type your message here...'
    }
  ]


  return (
    <>
      <Head>
        <title>Alex D's Cleaning Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconAlex.ico" />
      </Head>
      <div className={styles.second_nav} >
          <Navbar/>
      </div>
      <main>

      <div className={styles.first_container}>

        <div className={styles.bg_container}>

        </div>
        
        <div className={styles.welcome_container}>
          <h1>
          Welcome to Alex D's Cleaning Services
          </h1>
          
          <p>
          Our talented team works hard everyday to provide the best 
          services for our clients by personalizing our 
          services to your specific needs. Get in touch today to see how we can help you!
          </p>

          <div>
            <Link href={'/contact'}>free quote</Link>
            <Link href={'/services'}>services</Link>
          </div>
        </div>
      </div>

      <div className={styles.second_container}>

        <div className={styles.bg_container}>

        </div>

        <div className={styles.about_container}>
            <div>
              <h3>More About Us</h3>
              <p>
                Since our founding, Alex D's Cleaning Services has been known for quality 
                services and exceptional efficiency. No matter what service you’re looking for, 
                we guarantee to not only meet, but exceed your expectations and ensure your full satisfaction.
              </p>
              <p>
              Our team is up for every job, managing projects with the skill 
              and experience our clients have come to expect. Please get in touch to learn more
               about our team, our company or for details about the services we provide.
              </p>

              <Link href={'/about'}>about us</Link>
            </div>
        </div>
      </div>

      <div className={styles.three_container}>
        <h1>Our Services</h1>

        <div>
          <div className={styles.card}>
            <Image src={vector1}></Image>
            <Link href={'/services'}>deep cleaning</Link>
          </div>
          <div className={styles.card}>
            <Image src={vector2}></Image>
            <Link href={'/services'}>carpet / pressure cleaning</Link>

          </div>
          <div className={styles.card}>
            <Image src={vector3}></Image>
            <Link href={'/services'}>recurring cleaning</Link>

          </div>
          <div className={styles.card}>
            <Image src={vector4}></Image>
            <Link href={'/services'}>additional services</Link>

          </div>
        </div>

      </div>

      <div className={styles.fourth_container}>
        <div>

          <div className={styles.head_text} >
            <h2>
            Get a Free Quote Now!
            </h2>
            <p>Questions, comments or requests? Feel free to reach out, we’d love to hear from you.</p>
            <div>
            <p>Cape Coral, Florida</p>
            <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
            <a href="tel:+12392343355">(239)-234-3355</a>
            </div>

          </div>
            
            <form action="">
                {
                  fields.map((field) => (
                    <div>
                        <label htmlFor="">{field.name}</label>
                      {
                      field.type == 'text' || field.type == 'email' ?
                      <input type={field.type} placeholder={field.placeholder} />: 
                      <textarea placeholder={field.placeholder} ></textarea>
                      }
                    </div>
                  ))
                }

                <button>submit</button>
            </form>
            <div className={styles.contact}>
            <p>Cape Coral, Florida</p>
            <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
            <a href="tel:+12392343355">(239)-234-3355</a>
            </div>





        </div>
      </div>

      <div className={styles.nav_container}>
        <Link href='/'>home</Link>
        <Link href='/services'>services</Link>
        <Link href='/recent-work'>testimonials</Link>
        <Link href='/contact'>contact us</Link>
      </div>

      <footer className={styles.footer}>
        <div>
          <h1><Link href={'/'}>Alex D's Cleaning Service LLC</Link></h1>

          <div>
          <a href="mailto:alexdscleaning@gmail.com">alexdscleaning@gmail.com</a>
          <a href="tel:+12392343355">(239)-234-3355</a>
          </div>

          <p>©2023 by Alex D's Cleaning Service LLC.</p>
        </div>
      </footer>


      </main>
    </>
  )
}
